"""Domain enumerations for review workflow and evidence taxonomy."""

from __future__ import annotations

from enum import StrEnum


class OperationStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"


class SectorStatus(StrEnum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    REVIEWED = "REVIEWED"
    REQUIRES_REFLIGHT = "REQUIRES_REFLIGHT"


class SectorPriority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class IndexingStatus(StrEnum):
    PENDING = "PENDING"
    INDEXED = "INDEXED"
    MISSING_FILE = "MISSING_FILE"
    ERROR = "ERROR"


class ReviewStatus(StrEnum):
    NOT_REVIEWED = "NOT_REVIEWED"
    REVIEWED_CLEAR = "REVIEWED_CLEAR"
    REVIEWED_POOR = "REVIEWED_POOR"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REVIEWED_WITH_CANDIDATES = "REVIEWED_WITH_CANDIDATES"
    REQUIRES_REFLIGHT = "REQUIRES_REFLIGHT"


class QualityIssue(StrEnum):
    FOG = "FOG"
    MOTION_BLUR = "MOTION_BLUR"
    OVEREXPOSURE = "OVEREXPOSURE"
    UNDEREXPOSURE = "UNDEREXPOSURE"
    CAMERA_TOO_FAST = "CAMERA_TOO_FAST"
    INSUFFICIENT_RESOLUTION = "INSUFFICIENT_RESOLUTION"
    TERRAIN_OCCLUSION = "TERRAIN_OCCLUSION"
    GLACIER_CRACK = "GLACIER_CRACK"
    FATIGUE_RISK = "FATIGUE_RISK"
    UNKNOWN = "UNKNOWN"


class CandidateCategory(StrEnum):
    PERSON_LIKE = "PERSON_LIKE"
    DARK_SPOT = "DARK_SPOT"
    ANOMALOUS_SHADOW = "ANOMALOUS_SHADOW"
    SHORT_GLINT = "SHORT_GLINT"
    EQUIPMENT = "EQUIPMENT"
    ROPE_OR_LINEAR_OBJECT = "ROPE_OR_LINEAR_OBJECT"
    CLOTHING_OR_FABRIC = "CLOTHING_OR_FABRIC"
    TRACKS = "TRACKS"
    BIVOUAC = "BIVOUAC"
    SNOW_CAVE = "SNOW_CAVE"
    SLIDE_OR_FALL_TRACE = "SLIDE_OR_FALL_TRACE"
    DISTURBED_SNOW = "DISTURBED_SNOW"
    FRESH_ROCK = "FRESH_ROCK"
    TERRAIN_HAZARD = "TERRAIN_HAZARD"
    OTHER = "OTHER"


class EvidenceTag(StrEnum):
    GEOMETRY = "GEOMETRY"
    SHORT_GLINT = "SHORT_GLINT"
    ANOMALOUS_SHADOW = "ANOMALOUS_SHADOW"
    DARK_ON_SNOW = "DARK_ON_SNOW"
    TEMPORAL_CHANGE = "TEMPORAL_CHANGE"
    POSSIBLE_MOVEMENT = "POSSIBLE_MOVEMENT"
    COLOR_ANOMALY = "COLOR_ANOMALY"
    LINEAR_OBJECT = "LINEAR_OBJECT"
    REGULAR_SHAPE = "REGULAR_SHAPE"
    CONTEXTUAL_RISK = "CONTEXTUAL_RISK"


class TerrainFeature(StrEnum):
    BERGSCHRUND = "BERGSCHRUND"
    RANDKLUFT = "RANDKLUFT"
    CREVASSE = "CREVASSE"
    ICEFALL = "ICEFALL"
    COULOIR = "COULOIR"
    COULOIR_EXIT = "COULOIR_EXIT"
    ROCKFALL_ZONE = "ROCKFALL_ZONE"
    DEBRIS_CONE = "DEBRIS_CONE"
    ROCK_LEDGE = "ROCK_LEDGE"
    ROCK_NICHE = "ROCK_NICHE"
    OVERHANG = "OVERHANG"
    MELTWATER_CHANNEL = "MELTWATER_CHANNEL"
    GLACIER_EDGE = "GLACIER_EDGE"
    SNOW_DEPRESSION = "SNOW_DEPRESSION"


class SessionState(StrEnum):
    IDLE = "IDLE"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    ENDED = "ENDED"


class FatigueWarningLevel(StrEnum):
    NONE = "NONE"
    BREAK_RECOMMENDED = "BREAK_RECOMMENDED"
    STRONG_WARNING = "STRONG_WARNING"
    HIGH_RISK = "HIGH_RISK"
